import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Footer } from "@/components/Layout/Footer";
import { Header } from "@/components/Layout/Header";
import "./globals.css";

const fonts = Inter({
  variable: "--font-primary",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fonts.variable} antialiased bg-background text-primary`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
